-- Run this in the Supabase SQL editor before deploying to Cloudflare Pages.
-- Then create an admin user in Supabase Auth using email/password.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text,
  category text not null default 'Maison',
  price numeric not null default 0,
  old_price numeric,
  stock integer,
  active boolean not null default true,
  title jsonb not null default '{"ar":"","fr":""}'::jsonb,
  description jsonb not null default '{"ar":"","fr":""}'::jsonb,
  highlights jsonb not null default '{"ar":[],"fr":[]}'::jsonb,
  box jsonb not null default '{"ar":"","fr":""}'::jsonb,
  images jsonb not null default '[]'::jsonb,
  variants jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer jsonb not null,
  items jsonb not null default '[]'::jsonb,
  total numeric not null default 0,
  status text not null default 'new',
  source text not null default 'storefront_whatsapp',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  id text primary key default 'main',
  store_name text not null default 'CasaTanja',
  whatsapp_number text not null default '212708012888',
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id text primary key,
  title jsonb not null default '{"ar":"","fr":""}'::jsonb,
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics (
  id bigint generated by default as identity primary key,
  event text not null,
  product_id bigint,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  created_at timestamptz not null default now()
);

-- After creating an Auth user, approve that user as an admin with:
-- insert into public.admin_users (user_id, email)
-- select id, email from auth.users where email = 'you@example.com'
-- on conflict (user_id) do nothing;

insert into public.settings (id, store_name, whatsapp_number)
values ('main', 'CasaTanja', '212708012888')
on conflict (id) do nothing;

insert into public.categories (id, title, sort_order)
values
  ('Maison', '{"ar":"المنزل","fr":"Maison"}'::jsonb, 10),
  ('Cuisine', '{"ar":"مطبخ","fr":"Cuisine"}'::jsonb, 20),
  ('Tech', '{"ar":"تقنية","fr":"Tech"}'::jsonb, 30),
  ('Beaute', '{"ar":"جمال","fr":"Beaute"}'::jsonb, 40),
  ('Clothing', '{"ar":"ملابس","fr":"Clothing"}'::jsonb, 50)
on conflict (id) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists set_settings_updated_at on public.settings;
create trigger set_settings_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

drop trigger if exists set_categories_updated_at on public.categories;
create trigger set_categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.settings enable row level security;
alter table public.categories enable row level security;
alter table public.analytics enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

grant execute on function public.is_admin() to authenticated;

drop policy if exists "Admins can read own admin status" on public.admin_users;
create policy "Admins can read own admin status"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
using (active = true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
on public.products for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders for insert
with check (status = 'new');

drop policy if exists "Admins can manage orders" on public.orders;
create policy "Admins can manage orders"
on public.orders for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read settings" on public.settings;
create policy "Public can read settings"
on public.settings for select
using (true);

drop policy if exists "Public can read active categories" on public.categories;
create policy "Public can read active categories"
on public.categories for select
using (active = true);

drop policy if exists "Admins can manage categories" on public.categories;
create policy "Admins can manage categories"
on public.categories for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage settings" on public.settings;
create policy "Admins can manage settings"
on public.settings for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can create analytics" on public.analytics;
create policy "Public can create analytics"
on public.analytics for insert
with check (true);

drop policy if exists "Admins can read analytics" on public.analytics;
create policy "Admins can read analytics"
on public.analytics for select
to authenticated
using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read product images" on storage.objects;
create policy "Public can read product images"
on storage.objects for select
using (bucket_id = 'product-images');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'product-images' and public.is_admin())
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images' and public.is_admin());
