-- Run this in the Supabase SQL editor before deploying to Cloudflare Pages.
-- Then create an admin user in Supabase Auth using email/password.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text,
  category text not null default 'Maison',
  price numeric not null default 0,
  old_price numeric,
  stock integer,
  active boolean not null default true,
  featured boolean not null default false,
  title jsonb not null default '{"ar":"","fr":""}'::jsonb,
  description jsonb not null default '{"ar":"","fr":""}'::jsonb,
  highlights jsonb not null default '{"ar":[],"fr":[]}'::jsonb,
  box jsonb not null default '{"ar":"","fr":""}'::jsonb,
  images jsonb not null default '[]'::jsonb,
  variants jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer jsonb not null,
  items jsonb not null default '[]'::jsonb,
  total numeric not null default 0,
  status text not null default 'new',
  source text not null default 'storefront_whatsapp',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  id text primary key default 'main',
  store_name text not null default 'CasaTanja',
  whatsapp_number text not null default '212708012888',
  featured_product_id bigint,
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics (
  id bigint generated by default as identity primary key,
  event text not null,
  product_id bigint,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.settings (id, store_name, whatsapp_number, featured_product_id)
values ('main', 'CasaTanja', '212708012888', null)
on conflict (id) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists set_settings_updated_at on public.settings;
create trigger set_settings_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.settings enable row level security;
alter table public.analytics enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
using (active = true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
on public.products for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders for insert
with check (status = 'new');

drop policy if exists "Admins can manage orders" on public.orders;
create policy "Admins can manage orders"
on public.orders for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read settings" on public.settings;
create policy "Public can read settings"
on public.settings for select
using (true);

drop policy if exists "Admins can manage settings" on public.settings;
create policy "Admins can manage settings"
on public.settings for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can create analytics" on public.analytics;
create policy "Public can create analytics"
on public.analytics for insert
with check (true);

drop policy if exists "Admins can read analytics" on public.analytics;
create policy "Admins can read analytics"
on public.analytics for select
to authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read product images" on storage.objects;
create policy "Public can read product images"
on storage.objects for select
using (bucket_id = 'product-images');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images');

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images');
